config/routes.rb
SampleApp::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy] # Section 9.1.1 Sessions Controller

  match '/signup',  :to => 'users#new'  # this works from HOME page

  match '/show',  :to => 'users#show'  

  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/home',    :to => 'pages#home'
  match '/help',    :to => 'pages#help'

  match '/index',   :to => 'pages#index' 

  match '/signup',  :to => 'users#new'        
  match '/signin',  :to => 'sessions#new'     
  match '/signout', :to => 'sessions#destroy' 

  root :to => "pages#home"

end

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Ruby on Rails Tutorial Sample App | <%= @title %></title>
</head>

<body>
   <h1>About Us</h1>

   <p>
   <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
   is a project to make a book and screencasts to teach web development
   with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
   is the sample application for the tutorial.
   </p>




 <!-- TEST (see Rails tutorial following Listing 5.2.1) -->
 <!-- NOTE: the lack of "=" sign for the assignment of local variable "logo" -->
 <!--  because we do NOT want this variable inserted into the template -->
   
 <!--	 IT WORKS  (BUT WHY DOES IT WORK OUTSIDE THE ROOT PATH ?)  -->
 <!--	  <% test01 = image_tag("test01.png", :alt => "test01", :class => "round") %>   -->
 <!--	  <%= link_to test01,  root_path %>                                             -->
 <!--	 Found answer: the 'path' is ignored;  --> 
 <!--	          Rails 3.1 uses built-in app/assets/images path --> 

	<% test01 = image_tag("test01.png", :alt => "test01", :class => "round ") %>


	<!--
	<%= link_to test01 %> 
   <p>Some text here</p>
   <p>Some more text here</p>
   <p>line 3 text here</p>
   <p>line 4 text here</p>
	 -->


  <TABLE class="samplet">
  <TR>
  		<TD> <%= link_to test01 %></TD>
  		<TD> 
			<p>Some text here and more and m and more and more</p>
			<p>Some more text here</p>
			<p>line 3 text here</p>
         <p>line 4 text here</p>
      </TD>
  </TR>
  </TABLE>
  </body>
  </html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ruby on Rails Tutorial Sample App | Contact</title>
</head>
<body>
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/feedback">feedback page</a>.
</p>
</body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>

<p>
   Get help on Ruby on Rails Tutorial at the
   <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
   To get help on this sample app, see the
   <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Ruby on Rails Tutorial Sample App | <%= @title %></title>
</head>

<body>
	<h1>Sample App</h1>

	<p>
		This is the home page for the
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</p>

	<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

</body>
</html> 

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>

<head>
	<title><%= @title %> | Ruby on Rails Tutorial Sample App</title>
</head>

<body>
	<h1><%= @title %> | Ruby on Rails Tutorial Sample App</h1>

	<h2>pages#index Hello</h2>
	<p></p>
	<p>Find me in app/views/pages/index.html.erb</p>

	<p></p>
	<p></p>

	<%= link_to "home", home_path %>
	<%= link_to "about", about_path %>
	<%= link_to "index", index_path %>

	<p></p>

</body>
</html>