config/routes.rb
SampleApp::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy] # Section 9.1.1 Sessions Controller

  match '/signup',  :to => 'users#new'  # this works from HOME page

  match '/show',  :to => 'users#show'  

  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/home',    :to => 'pages#home'
  match '/help',    :to => 'pages#help'

  match '/index',   :to => 'pages#index' 

  match '/signup',  :to => 'users#new'        
  match '/signin',  :to => 'sessions#new'     
  match '/signout', :to => 'sessions#destroy' 

  root :to => "pages#home"

end

app/views/layouts/[orig]application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
			<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
 	  <header>

		 <!-- in Apllication_helper.rb     -->
 	  	 <%= link_to logo, root_path %>


 		 <nav class="round">
 		 	 <ul>
 				<li><%= link_to "Home", root_path %></li>


				<!-- Listing 9.29 Adding a Profile link.  -->
				<!-- Listing 10.6 Adding a Settings (Edit) link  -->
				<% if signed_in? %>
					<li><%= link_to "Users", users_path %></li>    <!-- Listing 10.23   -->
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<% end %>

 				<li><%= link_to "Help", help_path %></li>
 			


			<!-- TEMP QQQR     -->
 		<!-- 		 <li><%= link_to "tempSHOW", show_path %></li>     -->


 
			<!-- Listing 9.26  Changing the layout links for signed-in users.   -->
			<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
			<% end %>



 			  </ul>
 		 </nav>
 	 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 


<head>

  <!--Note in particular the switch from the instance variable @title-->
  <!-- to the helper method title (without the @ sign).-->

  <title><%= title %></title>


  <!-- csrf_meta_tag  provides some sort of security -->
  <%= csrf_meta_tag %>





  <!-- see section 5.1.1   Rails 3 tutorial -->
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->



	<!-- ################################################################################## -->
	<!-- Listing 10.39 and preceding text: for effecting user deletion with javascript -->
	<!-- above no longer works; use following   -->
	<!-- http://ruby.railstutorial.org/chapters/rails-3-1#top -->

	<!-- old defunct
	<%= javascript_include_tag :defaults %>
	-->



	<!-- 
	<%= javascript_include_tag "application" %>
	-->

<%= javascript_include_tag "application.js","pages.js", "sessions.js", "users.js" %>



	<%= stylesheet_link_tag "application" %>

	<!-- ################################################################################## -->




  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>

 
  <!-- see section 5.1.1  Rails 3 tutorial  -->
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->


  <%= stylesheet_link_tag 'custom', :media => 'screen' %>


</head>



<body>

  <div class="container">
	  <%= render 'layouts/header' %>



   <section class="round">
      <!-- FLASH - see section 8.3.3  -->
   	<% flash.each do |key, value| %>
   		<div class="flash <%= key %>"><%= value %></div>
   	<% end %>

   	<%= yield %>
   </section>


	  <%= render 'layouts/footer' %>

     <!-- see section 6.3.1 Rails 3 tutorial -->	
	  <%= debug(params) if Rails.env.development? %>

  </div>

</body>
</html>